export const metadata = {
  alert: "Alert",
  "alert-dialog": "Alert Dialog",
  "aspect-ratio": "Aspect Ratio",
  avatar: "Avatar",
  badge: "Badge",
  breadcrumb: "Breadcrumb",
  button: "Button",
  calendar: "Calendar",
  carousel: "Carousel",
  chart: "Chart",
  checkbox: "Checkbox",
  chip: "Chip",
  collapsible: "Collapsible",
  controls: "Controls",
  "delta-chip": "Delta Chip",
  input: "Input",
  "input-otp": "Input OTP",
  kicker: "Kicker",
  kbd: "Keyboard Shortcut",
  label: "Label",
  "live-indicator": "Live Indicator",
  progress: "Progress",
  "radio-group": "Radio Group",
  select: "Select",
  separator: "Separator",
  skeleton: "Skeleton",
  slider: "Slider",
  spinner: "Spinner",
  switch: "Switch",
  textarea: "Textarea",
  toggle: "Toggle",
  "toggle-group": "Toggle Group",
  tooltip: "Tooltip",
};
