export default {
  alert: { title: "Alert" },
  "alert-dialog": { title: "Alert Dialog" },
  "aspect-ratio": { title: "Aspect Ratio" },
  avatar: { title: "Avatar" },
  badge: { title: "Badge" },
  breadcrumb: { title: "Breadcrumb" },
  button: { title: "Button" },
  calendar: { title: "Calendar" },
  carousel: { title: "Carousel" },
  chart: { title: "Chart" },
  checkbox: { title: "Checkbox" },
  chip: { title: "Chip" },
  collapsible: { title: "Collapsible" },
  controls: { title: "Controls" },
  input: { title: "Input" },
  "input-otp": { title: "Input OTP" },
  kicker: { title: "Kicker" },
  kbd: { title: "Keyboard Shortcut" },
  label: { title: "Label" },
  "live-indicator": { title: "Live Indicator" },
  pagination: { title: "Pagination" },
  progress: { title: "Progress" },
  "radio-group": { title: "Radio Group" },
  select: { title: "Select" },
  separator: { title: "Separator" },
  skeleton: { title: "Skeleton" },
  slider: { title: "Slider" },
  spinner: { title: "Spinner" },
  switch: { title: "Switch" },
  textarea: { title: "Textarea" },
  toggle: { title: "Toggle" },
  "toggle-group": { title: "Toggle Group" },
  tooltip: { title: "Tooltip" },
}
