export const metadata = {
  alert: "Alert",
  avatar: "Avatar",
  badge: "Badge",
  button: "Button",
  chip: "Chip",
  controls: "Controls",
  input: "Input",
  kicker: "Kicker",
  label: "Label",
  "live-indicator": "Live Indicator",
  progress: "Progress",
  "radio-group": "Radio Group",
  select: "Select",
  separator: "Separator",
  skeleton: "Skeleton",
  spinner: "Spinner",
  tooltip: "Tooltip",
};
